routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\SiteController@aboutIndex')->name('home');
//Admin Route Hear

Route::resource('Admin/About','Admin\AboutController')->middleware('auth');
Route::resource('Admin/SocialMedia','Admin\ScialMediaController')->middleware('auth');
Route::resource('Admin/Contact','Admin\ContactController')->middleware('auth');
Route::resource('Admin/Gallary','Admin\GallaryController')->middleware('auth');
Route::resource('Admin/MyCline','Admin\ContactUserController')->middleware('auth');
Route::resource('Admin/menu','Admin\MenuController')->middleware('auth');
Route::resource('Admin/subMenu', 'Admin\SubMenuController')->middleware('auth');
Route::resource('Admin/post', 'Admin\PostController')->middleware('auth');
Route::get('Admin/indexNews', 'Admin\PostController@indexNews')->middleware('auth');
Route::get('Admin/add/{id}', 'Admin\PostController@add')->middleware('auth');
Route::post('Admin/indexing/{id}', 'Admin\PostController@indexingUpload')->middleware('auth');
Route::post('Admin/indexingRemove/{id}', 'Admin\PostController@indexingRemove')->middleware('auth');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');
Route::get('/logout', 'HomeController@logout')->name('logout');




// Frontend Route

Route::get('singlePage','Frontend\SiteController@singlePage');
Route::get('categoryPage','Frontend\SiteController@categoryPage');

app/Http/Controllers/Admin/SubMenuController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\SubMenu;
use DB;
use App\Model\Admin\Menu;

class SubMenuController extends Controller
{
    public function index(){
    	$submenus=DB::table('sub_menus')->paginate(8);

    	return view('Admin.SubMenu.index')->with('submenu', $submenus);
    }
    public function create(){
    	$menus=Menu::all();

    	return view('Admin.SubMenu.create')->with('menu', $menus);
    }
    public function store(Request $request){
    	$submenu= new SubMenu;
    	$submenu->name=$request->name;
    	$submenu->description=$request->description;
    	$submenu->mainMenu=$request->mainMenu;
    	$submenu->status=0;

    	$submenu->save();
    	
    	$submenus=DB::table('sub_menus')->paginate(8);

    	return view('Admin.SubMenu.index')->with('submenu', $submenus);
    }
    public function edit($id){
        $subMenus=SubMenu::find($id);
        $menus=Menu::all();

        return view('Admin.SubMenu.edit')
        ->with('submenu', $subMenus)
        ->with('menu', $menus);
    }
    public function update(Request $request ,$id){
        $submenu=SubMenu::find($id);

        $submenu->name=$request->input('name');
        $submenu->description=$request->input('description');
        $submenu->mainMenu=$request->input('mainMenu');
        $submenu->status=$request->input('status');

        $submenu->save();
        
        $submenus=DB::table('sub_menus')->paginate(8);

        return view('Admin.SubMenu.index')->with('submenu', $submenus);
    }
}

resources/views/Admin/SubMenu/base.blade.php
@extends('Admin.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/Admin/SubMenu/create.blade.php
@extends('Admin.SubMenu.base')

@section('action-content')


<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>CREATE SUB MENU </h1>
		</div>
	</div>

<form class="form" action="{{route('subMenu.store')}} " method="POST" enctype="multipart/form-data">
	  @csrf

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label"> Title</label>
			<input type="text" name="name" class="form-control" required>
		<div class="help-block"></div>
			</div>

		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label"> Select Main Menu</label>
			<select name="mainMenu" class="form-control" required>
				@foreach($menu as $menus)
				<option value="{{$menus->id}}">{{$menus->name}}</option>
				@endforeach
			</select>
		<div class="help-block"></div>
			</div>

		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Description</label>
			<textarea name="description" class="form-control" id="description" required></textarea>
		<div class="help-block"></div>
		</div>
	</div>
	</div>	
</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/SubMenu/edit.blade.php
@extends('Admin.SubMenu.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>EDIT MENU </h1>
		</div>
	</div>

<form class="form" action="{{route('subMenu.update', [$submenu->id])}} " method="POST" enctype="multipart/form-data">
	   <input type="hidden" name="_method" value="PUT">
	  {{ csrf_field() }}

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label"> Title</label>
			<input type="text" name="name" class="form-control" value="{{$submenu->name}}" required>
		<div class="help-block"></div>
			</div>

			<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label"> Select Main Menu</label>
			<select name="mainMenu" class="form-control" required>
				<option  value="{{$submenu->mainMenu}}" disabled>{{$submenu->mainMenu}}</option>
				@foreach($menu as $menus)
				<option value="{{$menus->id}}">{{$menus->name}}</option>
				@endforeach
			</select>
		<div class="help-block"></div>
			</div>



		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Description</label>
			<textarea name="description" class="form-control" id="description" required>{{$submenu->description}}</textarea>
		<div class="help-block"></div>
		</div>
	</div>
			<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Status</label>
			<select name="status">
			<option hidden  value="{{$submenu->status}}">
				@if($submenu->status==0)
				Active
				@else
				Deactive
				@endif
			</option>
			<option value="0">Active</option>
			<option value="1">Deactive</option>
			</select>
		<div class="help-block"></div>
		</div>
	</div>
			
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Update</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/SubMenu/index.blade.php
@extends('Admin.SubMenu.base')

@section('action-content')

<div class="row">
	<div class="col-lg-12">
		<table class="table">
			<tr>
				<td>Sn</td>
				<td>Name</td>
				<td>Action</td>
				<td>
					<a href="{{route('subMenu.create')}}"  class="btn btn-primary btn-xm">Create</a>
				</td>
			</tr>
			@foreach($submenu as $submenus)
			<tr>

				<td>{{$submenus->id}}</td>
				<td>{{$submenus->name}}</td>
				<td>
					<a href="{{route('subMenu.edit', $submenus->id)}}"  class="btn btn-success">Edit</a>
					
			</tr>
			@endforeach
		</table>
	</div>
	
</div>

@endsection