routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\SiteController@aboutIndex')->name('home');
//Admin Route Hear

Route::resource('Admin/About','Admin\AboutController')->middleware('auth');
Route::resource('Admin/SocialMedia','Admin\ScialMediaController')->middleware('auth');
Route::resource('Admin/Contact','Admin\ContactController')->middleware('auth');
Route::resource('Admin/Gallary','Admin\GallaryController')->middleware('auth');
Route::resource('Admin/MyCline','Admin\ContactUserController')->middleware('auth');
Route::resource('Admin/menu','Admin\MenuController')->middleware('auth');
Route::resource('Admin/subMenu', 'Admin\SubMenuController')->middleware('auth');
Route::resource('Admin/post', 'Admin\PostController')->middleware('auth');
Route::get('Admin/indexNews', 'Admin\PostController@indexNews')->middleware('auth');
Route::get('Admin/add/{id}', 'Admin\PostController@add')->middleware('auth');
Route::post('Admin/indexing/{id}', 'Admin\PostController@indexingUpload')->middleware('auth');
Route::post('Admin/indexingRemove/{id}', 'Admin\PostController@indexingRemove')->middleware('auth');
Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');
Route::get('/logout', 'HomeController@logout')->name('logout');




// Frontend Route

Route::get('singlePage','Frontend\SiteController@singlePage');
Route::get('categoryPage','Frontend\SiteController@categoryPage');

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\Menu;
use DB;

class MenuController extends Controller
{
    public function index(){
    	$menus=DB::table('menus')->paginate(8);

    	return view('Admin.Menu.index')->with('menu', $menus);
    }
    public function create(){

    	return view('Admin.Menu.create');
    }
    public function store(Request $request){

    	$menu = new Menu;
    	$menu->name=$request->name;
    	$menu->description=$request->description;
    	$menu->status=0;

    	$menu->save();
    	$menus=DB::table('menus')->paginate(8);

    	return view('Admin.Menu.index')->with('menu', $menus);

    }
    public function edit($id){
    	$menus=Menu::find($id);

    	return view('Admin.Menu.edit')->with('menu', $menus);
    }
    public function update(Request $request, $id){
    	$menu=Menu::find($id);

    	$menu->name=$request->input('name');
    	$menu->description=$request->input('description');
    	$menu->status=$request->input('status');

    	$menu->save();

    	$menus=DB::table('menus')->paginate(8);

    	return view('Admin.Menu.index')->with('menu', $menus);
    }
}

resources/views/Admin/Menu/base.blade.php
@extends('Admin.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/Admin/Menu/create.blade.php
@extends('Admin.Menu.base')

@section('action-content')


<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>CREATE MENU </h1>
		</div>
	</div>

<form class="form" action="{{route('menu.store')}} " method="POST" enctype="multipart/form-data">
	  @csrf

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label"> Title</label>
			<input type="text" name="name" class="form-control" required>
		<div class="help-block"></div>
			</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Description</label>
			<textarea name="description" class="form-control" id="description" required></textarea>
		<div class="help-block"></div>
		</div>
	</div>
	</div>		
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/Menu/edit.blade.php
@extends('Admin.Menu.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>EDIT MENU </h1>
		</div>
	</div>

<form class="form" action="{{route('menu.update', [$menu->id])}} " method="POST" enctype="multipart/form-data">
	   <input type="hidden" name="_method" value="PUT">
	  {{ csrf_field() }}

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label"> Title</label>
			<input type="text" name="name" class="form-control" value="{{$menu->name}}" required>
		<div class="help-block"></div>
			</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Description</label>
			<textarea name="description" class="form-control" id="description" required>{{$menu->description}}</textarea>
		<div class="help-block"></div>
		</div>
	</div>
			<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Status</label>
			<select name="status">
			<option value="{{$menu->status}}">
				@if($menu->status==0)
				Active
				@else
				Deactive
				@endif
			</option>
			<option value="0">Active</option>
			<option value="1">Deactive</option>
			</select>
		<div class="help-block"></div>
		</div>
	</div>
</div>
			
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Update</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/Menu/index.blade.php
@extends('Admin.Menu.base')

@section('action-content')

<div class="row">
	<div class="col-lg-12">
		<table class="table">
			<tr>
				<td>Sn</td>
				<td>Name</td>
				<td>Action</td>
				<td>
					<a href="{{route('menu.create')}}"  class="btn btn-primary btn-xm">Create</a>
				</td>
			</tr>
			@foreach($menu as $menus)
			<tr>

				<td>{{$menus->id}}</td>
				<td>{{$menus->name}}</td>
				<td>
					<a href="{{route('menu.edit', $menus->id)}}"  class="btn btn-success">Edit</a>
					
			</tr>
			@endforeach
		</table>
		{{$menu->links()}}
	</div>
	
</div>

@endsection